#pragma once

#define TIMEOUT 3

#define FRACTION (10000)
#define FULL_PERSENT (1000000)

#define UPPER_BOUND (10000)
#define LOWER_BOUND (0)

#define TWO_DECIMAL_PLACES (100)
#define RECOVERY_PERIOD (432000)

//------------------------------------------

#define NUMBER_OF_CONVERSIONS (13)
#define TOTAL_TERM_OF_CONCLUSION 15
//#define TOTAL_TERM_OF_CONCLUSION (604800)
#define MIN_AMOUNT_VESTING_CONCLUSION (100000)

#define MIN_AMOUNT_DELEGATION_VESTING (50000)
#define MIN_PERIOD_DELEGATION (0)
#define MAX_PERSENT_DELEGATION (0)
#define TIME_LIMIT_FOR_RETURN_DELEGATE_VESTING 15
//#define TIME_LIMIT_FOR_RETURN_DELEGATE_VESTING (604800)
